# Generated by Django 3.1.4 on 2021-01-05 22:55

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('createdDate', models.DateField(default= timezone.now())),
                #('lastUpdatedDate', models.DateField()),
                ('grade', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
    ]
