# Generated by Django 3.1.4 on 2021-01-05 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='Id',
        ),
        migrations.AlterField(
            model_name='student',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 23, 14, 12, 400784)),
        ),
    ]
