# Generated by Django 3.1.4 on 2021-01-05 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_auto_20210105_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 23, 16, 26, 976440)),
        ),
    ]
